version: 2

jobs:
  install:
    docker: &BUILDIMAGE
      - image: jenkinsrise/cci-v2-components:0.0.4
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker: *BUILDIMAGE
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm test

  gcloud-setup:
    docker: &GCSIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.6
    steps:
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: mv private-keys ..
      - run: gcloud auth activate-service-account 452091732215@developer.gserviceaccount.com --key-file ../private-keys/storage-server/rva-media-library-ce0d2bd78b54.json
      - persist_to_workspace:
          root: ~/.config
          paths:
            - gcloud

  generate-version:
    docker: *BUILDIMAGE
    steps:
      - run: mkdir version-string
      - run: echo $(date +%Y.%m.%d.%H.%M) > version-string/version
      - persist_to_workspace:
          root: .
          paths:
            - version-string

  deploy-stage:
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: echo stage $(cat /tmp/shared-workspace/version-string/version)

  deploy-beta:
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: echo beta $(cat /tmp/shared-workspace/version-string/version)

  deploy-stable:
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: echo stable $(cat /tmp/shared-workspace/version-string/version)

workflows:
  version: 2
  workflow1:
    jobs:
      - install
      - gcloud-setup:
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - master
                - build/stable
      - generate-version
      - test:
          requires:
            - install
      - deploy-stage:
          requires:
            - gcloud-setup
            - generate-version
            - test
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
      - deploy-beta:
          requires:
            - gcloud-setup
            - generate-version
            - test
          filters:
            branches:
              only:
                - master
      - deploy-stable:
          requires:
            - gcloud-setup
            - generate-version
            - test
          filters:
            branches:
              only:
                - build/stable
