version: 2

jobs:
  build_and_test:
    docker: &BUILDIMAGE
      - image: jenkinsrise/cci-v2-components:0.0.4
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  workflow1:
    jobs:
      - build_and_test
