version: 2.1

jobs:
  preconditions:
    docker: &BUILDIMAGE
      - image: jenkinsrise/cci-v2-components:0.0.4
    steps:
      - run: |
          if [ -z "$COMPONENT_NAME" ]
          then
            echo Component name must be specified as an environment variable.
            exit 1
          fi

  install:
    docker: *BUILDIMAGE
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    docker: *BUILDIMAGE
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm test

  build:
    docker: *BUILDIMAGE
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  build-e2e-page:
    parameters:
      stage:
        type: string
    docker: *BUILDIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: echo build e2e page << parameters.stage >>
      - run: |
          sed '
            s/__STAGE__/<< parameters.stage >>/;
            s/__PLAYER__/electron/;
            s/__CONNECTION__/websocket/;
          ' e2e/rise-data-image.html > e2e/rise-data-image-electron.html
      - run: cp e2e/polymer-e2e-electron.json polymer.json
      - run: polymer build
      - persist_to_workspace:
          root: ./build
          paths:
            - base

  gcloud-setup:
    docker: &GCSIMAGE
      - image: jenkinsrise/cci-v2-launcher-electron:0.0.6
    steps:
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run: mv private-keys ..
      - run: gcloud auth activate-service-account 452091732215@developer.gserviceaccount.com --key-file ../private-keys/storage-server/rva-media-library-ce0d2bd78b54.json
      - persist_to_workspace:
          root: ~/.config
          paths:
            - gcloud

  generate-version:
    docker: *BUILDIMAGE
    steps:
      - run: mkdir version-string
      - run: echo $(date +%Y.%m.%d.%H.%M) > version-string/version
      - persist_to_workspace:
          root: .
          paths:
            - version-string

  deploy-stage:
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: |
          GS_BASE=gs://widgets.risevision.com
          VERSION=$(cat version-string/version)
          TARGET=$GS_BASE/staging/components/$COMPONENT_NAME/$VERSION/
          echo Deploying version $VERSION to $COMPONENT_NAME
          ./upload_to_gcs.sh $COMPONENT_NAME $TARGET

  deploy-production:
    parameters:
      stage:
        type: string
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: |
          GS_BASE=gs://widgets.risevision.com
          TARGET=$GS_BASE/<< parameters.stage >>/components/$COMPONENT_NAME/
          echo Deploying << parameters.stage >> version of $COMPONENT_NAME
          ./upload_to_gcs.sh $COMPONENT_NAME $TARGET

  deploy-e2e-page:
    parameters:
      stage:
        type: string
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: mkdir -p ~/.config
      - run: cp -r gcloud ~/.config
      - run: |
          GS_BASE=gs://widgets.risevision.com
          TARGET=$GS_BASE/<< parameters.stage >>/e2e/$COMPONENT_NAME/electron
          echo Deploying << parameters.stage >> electron e2e page for $COMPONENT_NAME
          gsutil rsync -d -r base $TARGET
          gsutil -m setmeta -r -h "Cache-Control:private, max-age=0" $TARGET
          gsutil acl -r ch -u AllUsers:R $TARGET

  test-e2e:
    parameters:
      stage:
        type: string
    docker: *GCSIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: echo testing e2e << parameters.stage >>

workflows:
  workflow1:
    jobs:
      - preconditions
      - install:
          requires:
            - preconditions
      - gcloud-setup:
          requires:
            - preconditions
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - master
                - build/stable
      - generate-version:
          requires:
            - preconditions
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - master
                - build/stable
      - test:
          requires:
            - install
      - build:
          requires:
            - test
      - build-e2e-page:
          stage: beta
          name: build-e2e-page-beta
          requires:
            - build
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - master
      - build-e2e-page:
          stage: stable
          name: build-e2e-page-stable
          requires:
            - build
          filters:
            branches:
              only:
                - build/stable
      - deploy-stage:
          requires:
            - gcloud-setup
            - generate-version
            - build
          filters:
            branches:
              only:
                - /^(stage|staging)[/].*/
                - master
                - build/stable
      - deploy-production:
          stage: beta
          name: deploy-beta
          requires:
            - gcloud-setup
            - generate-version
            - build
          filters:
            branches:
              only:
                - master
                - /^(stage|staging)[/].*/
      - deploy-production:
          stage: stable
          name: deploy-stable
          requires:
            - gcloud-setup
            - generate-version
            - build
          filters:
            branches:
              only:
                - build/stable
      - deploy-e2e-page:
          stage: beta
          name: deploy-e2e-page-beta
          requires:
            - build-e2e-page-beta
          filters:
            branches:
              only:
                - master
                - /^(stage|staging)[/].*/
      - deploy-e2e-page:
          stage: stable
          name: deploy-e2e-page-stable
          requires:
            - build-e2e-page-stable
          filters:
            branches:
              only:
                - build/stable
      - test-e2e:
          stage: beta
          name: test-e2e-beta
          requires:
            - deploy-beta
            - deploy-e2e-page-beta
          filters:
            branches:
              only:
                - master
                - /^(stage|staging)[/].*/
      - test-e2e:
          stage: stable
          name: test-e2e-stable
          requires:
            - deploy-stable
            - deploy-e2e-page-stable
          filters:
            branches:
              only:
                - build/stable
