version: 2

jobs:
  build_and_test:
    working_directory: ~/Rise-Vision/rise-data-image
    shell: /bin/bash --login
    docker: &BUILDIMAGE
      - image: jenkinsrise/cci-v2-transitional-widgets:0.0.1
        command: /sbin/init
    steps:
      - checkout
      - run: npm install
      - run: npm install -g polymer-cli
      - run: polymer test --npm

workflows:
  version: 2
  workflow1:
    jobs:
      - build_and_test
